name: Build APK
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: android-actions/setup-android@v3
      - run: chmod +x gradlew
      - run: ./gradlew :app_pojavlauncher:assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app_pojavlauncher/build/outputs/apk/debug/*.apk
